config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :lawyers do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  resources :restaurants 

  get 'pages/about'

  get 'pages/contact'

  root 'lawyers#index'

end

app/models/lawyer.rb
class Lawyer < ActiveRecord::Base
	mount_uploader :image, ImageUploader

    searchkick

	has_many :reviews

	validates :name, :address, :city, :state, :zip, :phone, :website, :practice, :image, presence: true
	validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
    message: "must be in the format (123) 456-7890" }
    validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
    message: "must start with http:// or https://" }
	validates :address, format: { with: /\A\d+[^,]+\z/,
    message: "must be in the format 123 Main Street" }
	validates :state, format: { with: /\A[a-zA-Z]{2}\z/,
    message: "must be two-letter capital abbreviation" }
    validates :zip, format: { with: /\A\d{5}\z/,
    message: "must be five number zip code" }
end

app/controllers/lawyers_controller.rb
class LawyersController < ApplicationController
  before_action :set_lawyer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:search, :index, :show]
  before_action :check_user, except: [:search, :index, :show]

  def search
    if params[:search].present?
      @lawyers = Lawyer.search(params[:search])
    else
      @laywers = Lawyer.all
    end
  end

  # GET /lawyers
  # GET /lawyers.json
  def index
    @lawyers = Lawyer.all
  end

  # GET /lawyers/1
  # GET /lawyers/1.json
  def show
    @reviews = Review.where(lawyer_id: @lawyer.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
    @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /lawyers/new
  def new
    @lawyer = Lawyer.new
  end

  # GET /lawyers/1/edit
  def edit
  end

  # POST /lawyers
  # POST /lawyers.json
  def create
    @lawyer = Lawyer.new(lawyer_params)

    respond_to do |format|
      if @lawyer.save
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully created.' }
        format.json { render :show, status: :created, location: @lawyer }
      else
        format.html { render :new }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawyers/1
  # PATCH/PUT /lawyers/1.json
  def update
    respond_to do |format|
      if @lawyer.update(lawyer_params)
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawyer }
      else
        format.html { render :edit }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawyers/1
  # DELETE /lawyers/1.json
  def destroy
    @lawyer.destroy
    respond_to do |format|
      format.html { redirect_to lawyers_url, notice: 'Lawyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lawyer
      @lawyer = Lawyer.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def lawyer_params
      params.require(:lawyer).permit(:name, :address, :city, :state, :zip, :phone, :website, :practice, :image)
    end
end

app/helpers/lawyers_helper.rb
module LawyersHelper
end

app/views/lawyers/_form.html.erb
<%= form_for(@lawyer, :html => { multipart: true }) do |f| %>
  <% if @lawyer.errors.any? %>
     <div id="error_explanation" class="alert alert-danger alert-dismissable">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@lawyer.errors.count, "error") %> prohibited this lawyer from being saved:</h4>

      <ul>
      <% @lawyer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Lawyer Name" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control", placeholder: "123 Street Name" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control", placeholder: "Cleveland" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.text_field :state, class: "form-control", placeholder: "OH" %>
  </div>
  <div class="form-group">
    <%= f.label :zip %><br>
    <%= f.text_field :zip, class: "form-control", placeholder: "44444" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "(123) 456-7890" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control", placeholder: "http://www.domain.com" %>
  </div>
  <div class="form-group">
    <%= f.label :practice %><br>
    <%= f.text_field :practice, class: "form-control", placeholder: "Personal Injury" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lawyers/edit.html.erb
<h1>Editing lawyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @lawyer, class: "btn btn-link" %> |
<%= link_to 'Back', lawyers_path, class: "btn btn-link" %>

app/views/lawyers/index.html.erb
<div class="jumbotron">
  <h2>LawyerJury is the best way to find reviews on local attorneys.</h2>
  <h3>Find legal experts in your community.<br>
Leave reviews and ratings to share your experience with others.</h3>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Practice</th>

      <% if user_signed_in? && current_user.admin? %>
      <th colspan="2"></th>
      <% end %>

    </tr>
  </thead>

  <tbody>
    <% @lawyers.each do |lawyer| %>
      <tr>
        <td><%= link_to lawyer.name, lawyer %></td>
        <td><%= lawyer.address %></td>
        <td><%= lawyer.city %></td>
        <td><%= lawyer.state %></td>
        <td><%= lawyer.zip %></td>
        <td><%= lawyer.phone %></td>
        <td><%= link_to lawyer.website, lawyer.website %></td>
        <td><%= lawyer.practice %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_lawyer_path(lawyer), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', lawyer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.admin? %>
<%= link_to 'New Lawyer', new_lawyer_path, class: "btn btn-link" %>
<% end %>

<%= image_tag "https://s3.amazonaws.com/ratejury/happy_footer.png" %>

app/views/lawyers/new.html.erb
<h1>New lawyer</h1>

<%= render 'form' %>

<%= link_to 'Back', lawyers_path, class: "btn btn-link" %>

app/views/lawyers/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Website</th>
      <th>Practice</th>

      <% if user_signed_in? && current_user.admin? %>
      <th colspan="2"></th>
      <% end %>

    </tr>
  </thead>

  <tbody>
    <% @lawyers.each do |lawyer| %>
      <tr>
        <td><%= link_to lawyer.name, lawyer %></td>
        <td><%= lawyer.address %></td>
        <td><%= lawyer.city %></td>
        <td><%= lawyer.state %></td>
        <td><%= lawyer.zip %></td>
        <td><%= lawyer.phone %></td>
        <td><%= link_to lawyer.website, lawyer.website %></td>
        <td><%= lawyer.practice %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_lawyer_path(lawyer), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', lawyer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lawyers/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @lawyer.image_url %>

<h2>
  <%= @lawyer.name %>
</h2>

<div class="star-rating" data-score= <%= @avg_rating %>></div>
<p><%= "#{@reviews.length} reviews" %></p>

<p>
  <strong>Address:</strong>
  <%= @lawyer.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @lawyer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @lawyer.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @lawyer.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lawyer.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= link_to @lawyer.website, @lawyer.website %>
</p>

<p>
  <strong>Practice:</strong>
  <%= @lawyer.practice %>
</p>

<%= link_to "Write a Review", new_lawyer_review_path(@lawyer), class: "btn btn-primary" %>

<br>
<br>

<iframe
  width="230"
  height="230"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAQs_7ufkG_GIwLtGAdwbqtQZcBsw22Tyg
    &q=<%= @lawyer.address+@lawyer.city+@lawyer.state+@lawyer.zip.parameterize %>&zoom=14">
</iframe>
  </div>

  <div class="col-md-8">
    <% if @reviews.blank? %>
      <h3>No reviews yet. Be the first to write one!</h3>
      <% else %>
      <h4>Recent Reviews</h4>
      <table class="table">
        <thead>
          <tr>
          <th class="col-md-3"></th>
          <th class="col-md-9"></th>
        </tr>
      </thead>

        <tbody>
          <% @reviews.each do |review| %>
            <tr>
            <td>
              <h4>
              <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
              </h4>
            <p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
          </td>

              <td>
                <div class="star-rating" data-score= <%= review.rating %>></div>
                <p><%= h(review.comment).gsub(/\n/, '</br>').html_safe %></p>

                <% if user_signed_in? %>
                  <% if (review.user == current_user) || (current_user.admin?) %>
                  <%= link_to "Edit", edit_lawyer_review_path(@lawyer, review) %>
                  <%= link_to "Delete", lawyer_review_path(@lawyer, review), method: :delete %>
                  <% end %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_lawyer_path(@lawyer), class: "btn btn-link" %> |
<%= link_to 'Back', lawyers_path, class: "btn btn-link" %>

<script>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/ratejury/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
  }
  });
</script>